app: fabo-back
service: fabo-api
name: fabo-api
useDotenv: true

package:
  individually: true
  exclude:
    - 'logs/**'
    - '.git/**'
    - 'serverless-configs/**'
    - 'node_modules/.cache/**'
    - 'db/**'

provider:
  name: aws
  runtime: nodejs14.x
  # stage: dev
  region: us-east-1
  # CHANGE fpaboim-fabo TO YOUR BUCKET NAME
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: arn:aws:s3:::fpaboim-fabo/*
    - Effect: "Allow"
      Action:
        - "s3:PutObjectAcl"
      Resource: arn:aws:s3:::fpaboim-fabo/*
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: arn:aws:s3:::fpaboim-fabo

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  app:
    handler: bundle.startApp
    externals:
      report: .dist/node-externals-report.json
    package:
      patterns:
        - "!./**"
        - ./.dist/bundle.js
    # events:
    #   - http: ANY /
    #   - http: 'ANY {proxy+}'
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Accept
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Accept
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

custom:
  config: rollup.config.js
  apiGatewayThrottling:
    maxRequestsPerSecond: 1000
    maxConcurrentRequests: 500
  serverless-offline:
    # noPrependStageInUrl: true
    # httpsProtocol: "dev-certs"
    httpPort: 4000
    host: 0.0.0.0
